// Generated by tools/android/import_assets.sh. Do not edit: rerun the script.
package app.plead.android.designsystem

/**
 * Every image imported from `ArgueWin/Resources/Assets.xcassets` into `res/drawable-nodpi`, with the
 * iOS scale of the file that was taken (the largest). An image drawn at iOS point size `w x h`
 * is `pixelWidth / scale` by `pixelHeight / scale` dp.
 */
object PleadAssets {
    val scales: Map<String, Int> = mapOf(
        "courtroom_background" to 1, // CourtroomBackground.imageset
        "frame1_courthouse" to 1, // ColdOpen/frame1_courthouse.imageset
        "frame2_door_left" to 1, // ColdOpen/frame2_door_left.imageset
        "frame2_door_right" to 1, // ColdOpen/frame2_door_right.imageset
        "frame2_doors" to 1, // ColdOpen/frame2_doors.imageset
        "frame2_doors_ajar" to 1, // ColdOpen/frame2_doors_ajar.imageset
        "frame2_doors_closed" to 1, // ColdOpen/frame2_doors_closed.imageset
        "frame3_judge" to 1, // ColdOpen/frame3_judge.imageset
        "frame4_gavel_1" to 1, // ColdOpen/frame4_gavel_1.imageset
        "frame4_gavel_2" to 1, // ColdOpen/frame4_gavel_2.imageset
        "frame4_gavel_3" to 1, // ColdOpen/frame4_gavel_3.imageset
        "frame4_gavel_4" to 1, // ColdOpen/frame4_gavel_4.imageset
        "frame4_gavel_5" to 1, // ColdOpen/frame4_gavel_5.imageset
        "frame5_endcard" to 1, // ColdOpen/frame5_endcard.imageset
        "onboarding_courtroom_hero" to 3, // OnboardingCourtroomHero.imageset
        "paywall_courtroom" to 3, // PaywallCourtroom.imageset
        "paywall_courtroom_bg" to 3, // PaywallCourtroomBG.imageset
        "paywall_defendant_idle" to 3, // PaywallDefendant_idle.imageset
        "paywall_defendant_react" to 3, // PaywallDefendant_react.imageset
        "paywall_defendant_talk_a" to 3, // PaywallDefendant_talkA.imageset
        "paywall_defendant_talk_b" to 3, // PaywallDefendant_talkB.imageset
        "paywall_judge_blink" to 3, // PaywallJudge_blink.imageset
        "paywall_judge_gavel_down" to 3, // PaywallJudge_gavelDown.imageset
        "paywall_judge_gavel_recoil" to 3, // PaywallJudge_gavelRecoil.imageset
        "paywall_judge_gavel_up" to 3, // PaywallJudge_gavelUp.imageset
        "paywall_judge_idle1" to 3, // PaywallJudge_idle1.imageset
        "paywall_judge_idle2" to 3, // PaywallJudge_idle2.imageset
        "paywall_plaintiff_idle" to 3, // PaywallPlaintiff_idle.imageset
        "paywall_plaintiff_react" to 3, // PaywallPlaintiff_react.imageset
        "paywall_plaintiff_talk_a" to 3, // PaywallPlaintiff_talkA.imageset
        "paywall_plaintiff_talk_b" to 3, // PaywallPlaintiff_talkB.imageset
        "plead_heart" to 3, // Brand/PleadHeart.imageset
        "plead_heart_scales" to 3, // Brand/PleadHeartScales.imageset
        "plead_logo_dark" to 3, // Brand/PleadLogoDark.imageset
        "plead_logo_light" to 3, // Brand/PleadLogoLight.imageset
        "plead_logo_mono" to 3, // Brand/PleadLogoMono.imageset
        "plead_scales" to 3, // Brand/PleadScales.imageset
        "plead_wordmark" to 3, // Brand/PleadWordmark.imageset
        "plead_wordmark_only" to 3, // Brand/PleadWordmarkOnly.imageset
        "plead_wordmark_reversed" to 3, // Brand/PleadWordmarkReversed.imageset
    )

    /** iOS scale of drawable [name] (1 when unknown). */
    fun scale(name: String): Int = scales[name] ?: 1
}
