// The pixel avatar must be pixel-identical to iOS. `src/test/resources/pixel_avatar_golden.txt` was generated by
// running the iOS source itself (`PixelAvatar.grid(for:)` and `outline(of:)`, copied verbatim from
// ArgueWin/DesignSystem/PixelAvatar.swift with a Color shim; see `pixel_avatar_golden.swift` next to it:
// `swift pixel_avatar_golden.swift > pixel_avatar_golden.txt`) for every hairstyle × outfit and six palette
// combinations, including out-of-range indices that must clamp.
package app.plead.android.designsystem

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.toArgb
import app.plead.android.models.Avatar
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

class PixelAvatarTests {
    private data class Case(val avatar: Avatar, val rows: List<String>, val outline: String)

    private fun golden(): List<Case> {
        val lines = javaClass.classLoader!!.getResource("pixel_avatar_golden.txt")!!.readText().trimEnd().lines()
        val out = mutableListOf<Case>()
        var i = 0
        while (i < lines.size) {
            val header = lines[i].removePrefix("# ").split(" ")
            val avatar = Avatar(
                skin = header[2].toInt(), hair = header[3].toInt(), hairstyle = Avatar.Hairstyle.valueOf(header[0]),
                top = header[4].toInt(), outfit = Avatar.Outfit.valueOf(header[1]),
            )
            out.add(Case(avatar, lines.subList(i + 1, i + 17), lines[i + 17].removePrefix("O").trim()))
            i += 18
        }
        return out
    }

    private fun token(c: Color?): String {
        if (c == null) return "."
        val argb = c.toArgb()
        return String.format("%06X%02X", argb and 0xFFFFFF, (argb ushr 24) and 0xFF)
    }

    @Test fun gridMatchesIOSGolden() {
        val cases = golden()
        assertEquals(6 * 5 * 6, cases.size)
        for (case in cases) {
            val grid = PixelAvatar.grid(case.avatar)
            assertEquals(PixelAvatar.side, grid.size)
            val rows = grid.map { row -> row.joinToString(" ") { token(it) } }
            assertEquals("grid for ${case.avatar}", case.rows, rows)
        }
    }

    @Test fun outlineMatchesIOSGolden() {
        for (case in golden()) {
            val outline = PixelAvatar.outline(PixelAvatar.grid(case.avatar)).joinToString(" ") { "${it.first},${it.second}" }
            assertEquals("outline for ${case.avatar}", case.outline, outline)
        }
    }

    @Test fun everyStyleAndOutfitIsCovered() {
        val cases = golden()
        assertEquals(Avatar.Hairstyle.entries.toSet(), cases.map { it.avatar.hairstyle }.toSet())
        assertEquals(Avatar.Outfit.entries.toSet(), cases.map { it.avatar.outfit }.toSet())
    }

    @Test fun darkenIsSixtyFivePercentTruncated() {
        assertEquals(0x591C1B, PixelAvatar.darken(0x8A2C2A))
        assertEquals(0x000000, PixelAvatar.darken(0x010101))
    }

    @Test fun clampKeepsIndicesInRange() {
        assertEquals(0, PixelAvatar.clamp(-1, 6))
        assertEquals(5, PixelAvatar.clamp(99, 6))
        assertEquals(3, PixelAvatar.clamp(3, 6))
    }

    @Test fun descriptionNamesHairAndOutfit() {
        val a = Avatar(skin = 4, hair = 0, hairstyle = Avatar.Hairstyle.curly, top = 5, outfit = Avatar.Outfit.hoodie)
        assertEquals("Pixel avatar: curly hair, hoodie", PixelAvatar.description(a))
        assertEquals(listOf("Buzz", "Short", "Long", "Curly", "Bun", "Ponytail"), Avatar.Hairstyle.entries.map { it.title })
        assertEquals(listOf("Tee", "Hoodie", "Shirt", "Dress", "Suit"), Avatar.Outfit.entries.map { it.title })
    }

    /** Cells snap to whole points (dp) from 32 wide; smaller badges use fractional cells that fill the frame. */
    @Test fun cellsSnapToWholePointsWhenLargeEnough() {
        val (cell48, inset48) = PixelAvatar.cellLayout(48f)
        assertEquals(3f, cell48); assertEquals(0f, inset48)
        val (cell40, inset40) = PixelAvatar.cellLayout(40f)
        assertEquals(2f, cell40); assertEquals(4f, inset40)
        val (cell28, inset28) = PixelAvatar.cellLayout(28f)
        assertEquals(1.75f, cell28); assertEquals(0f, inset28)
        assertTrue(PixelAvatar.cellLayout(37.84f).first == 2f)
    }
}
