// Port of ArgueWin/Features/Paywall/PaywallCourtroomSprites.swift.
//
// The paywall courtroom as layers (CONTRACTS-v2 amendment v). Generated by `tools/paywall-sprites/make_sprites.py`
// from the flattened `PaywallCourtroom` art: `PaywallCourtroomBG` is that art unchanged, and each character's frames
// are one fixed rect of it (same canvas for every frame), transparent wherever the frame equals the background.
// Drawing a frame at its rect's offset therefore only changes what the frame changes: no jump, no seam.
// Keep the rects below in sync with `RECTS` in the script. The PNGs are `res/drawable-nodpi/paywall_*` (the @3x
// images, snake_case names; `tools/android/import_assets.sh`).
package app.plead.android.features.paywall

import androidx.annotation.DrawableRes
import androidx.compose.ui.geometry.Rect
import androidx.compose.ui.geometry.Size
import app.plead.android.R

object PaywallCourtroomSprites {
    /** The source art in pixels (@3x). */
    val sourcePixels = Size(941f, 840f)
    const val sourceScale: Float = 3f
    const val background = "PaywallCourtroomBG"

    @DrawableRes val backgroundDrawable: Int = R.drawable.paywall_courtroom_bg

    enum class Character(val rawValue: String) {
        judge("Judge"), plaintiff("Plaintiff"), defendant("Defendant");

        /** The character's frame rect, in source pixels (origin top-left). */
        val rect: Rect
            get() = when (this) {
                judge -> Rect(326f, 470f, 326f + 206f, 470f + 136f)
                plaintiff -> Rect(100f, 690f, 100f + 76f, 690f + 50f)
                defendant -> Rect(770f, 700f, 770f + 56f, 700f + 46f)
            }

        val frameNames: List<String>
            get() = when (this) {
                judge -> JudgeFrame.entries.map { it.assetName }
                plaintiff, defendant -> PartnerFrame.entries.map { it.assetName(this) }
            }

        /** The drawables of [frameNames], in the same order. */
        val frameDrawables: List<Int>
            get() = when (this) {
                judge -> JudgeFrame.entries.map { it.drawable }
                plaintiff, defendant -> PartnerFrame.entries.map { it.drawable(this) }
            }
    }
}

/** Judge Wigsworth: idle (two breathing frames), blink, and the gavel swing (raised → struck → recoil). */
enum class JudgeFrame {
    idle1, idle2, blink, gavelUp, gavelDown, gavelRecoil;

    val rawValue: String get() = name
    val assetName: String get() = "PaywallJudge_$rawValue"
    val isGavel: Boolean get() = this == gavelUp || this == gavelDown || this == gavelRecoil

    @get:DrawableRes
    val drawable: Int
        get() = when (this) {
            idle1 -> R.drawable.paywall_judge_idle1
            idle2 -> R.drawable.paywall_judge_idle2
            blink -> R.drawable.paywall_judge_blink
            gavelUp -> R.drawable.paywall_judge_gavel_up
            gavelDown -> R.drawable.paywall_judge_gavel_down
            gavelRecoil -> R.drawable.paywall_judge_gavel_recoil
        }
}

/** The plaintiff (left stand) and defendant (right stand): neutral, two talking mouths, a pressed-lips reaction. */
enum class PartnerFrame {
    idle, talkA, talkB, react;

    val rawValue: String get() = name
    fun assetName(who: PaywallCourtroomSprites.Character): String = "Paywall${who.rawValue}_$rawValue"
    val isTalking: Boolean get() = this == talkA || this == talkB

    @DrawableRes
    fun drawable(who: PaywallCourtroomSprites.Character): Int = when (who) {
        PaywallCourtroomSprites.Character.defendant -> when (this) {
            idle -> R.drawable.paywall_defendant_idle
            talkA -> R.drawable.paywall_defendant_talk_a
            talkB -> R.drawable.paywall_defendant_talk_b
            react -> R.drawable.paywall_defendant_react
        }
        else -> when (this) {
            idle -> R.drawable.paywall_plaintiff_idle
            talkA -> R.drawable.paywall_plaintiff_talk_a
            talkB -> R.drawable.paywall_plaintiff_talk_b
            react -> R.drawable.paywall_plaintiff_react
        }
    }
}

/** What the three characters show right now. */
data class CourtroomPose(
    val judge: JudgeFrame = JudgeFrame.idle1,
    val plaintiff: PartnerFrame = PartnerFrame.idle,
    val defendant: PartnerFrame = PartnerFrame.idle,
) {
    companion object {
        val rest = CourtroomPose()
    }
}

/**
 * Where the art lands inside a hero of a given size: aspect-fill, bottom-aligned, centred horizontally (exactly the
 * placement of the old single-image `PaywallHero`), plus the conversion of source-pixel rects into that space.
 */
data class PaywallCourtroomPlacement(
    /** The whole art's frame in the hero's coordinates (it overflows the hero; the hero clips). */
    val art: Rect,
    /** Points per source pixel. */
    val pointsPerPixel: Float,
) {
    /** A source-pixel rect in the art's own coordinates (origin at the art's top-left). */
    fun inArt(r: Rect): Rect = Rect(
        r.left * pointsPerPixel, r.top * pointsPerPixel,
        r.right * pointsPerPixel, r.bottom * pointsPerPixel,
    )

    companion object {
        operator fun invoke(hero: Size): PaywallCourtroomPlacement {
            val src = PaywallCourtroomSprites.sourcePixels
            val fill = maxOf(hero.width / src.width, hero.height / src.height)
            val size = Size(src.width * fill, src.height * fill)
            val left = (hero.width - size.width) / 2
            val top = hero.height - size.height
            return PaywallCourtroomPlacement(art = Rect(left, top, left + size.width, top + size.height), pointsPerPixel = fill)
        }
    }
}
